#!/bin/bash
set -eu
if [ $# -ne 1 ]; then
  >&2 cat <<EOF
Usage: $0 ppa:user/repo
EOF
  exit 2
fi

user_and_repo=${1#*:}
user=${user_and_repo%/*}
repo=${user_and_repo#*/}

distribution=$(lsb_release -cs)

key_dir=/etc/apt/keyrings
key_basename="$user-ubuntu-$repo-$distribution"
key_path="$key_dir/$key_basename.asc"

apt_list_path="/etc/apt/sources.list.d/ppa-$user-$repo-$distribution.list"

if [ ! -f "$key_path" ]; then
  [ "$(2>/dev/null dpkg-query -f \${Status} -W curl)" != "install ok installed" ] && sudo apt-get install -y curl

  sudo mkdir -p $(dirname "$key_path")
  key_fingerprint=$(curl -sS "https://launchpad.net/~$user/+archive/ubuntu/$repo" | sed -n '/<dt>Fingerprint:<\/dt>/{n;s/.*<dd>//;s|</dd>||;p}')
  sudo curl -sS -o "$key_path" "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x$key_fingerprint"
fi

if [ ! -f "$apt_list_path" ]; then
  cat <<EOF | sudo tee "$apt_list_path" > /dev/null
deb [arch=$(dpkg --print-architecture) signed-by=$key_path] https://ppa.launchpadcontent.net/$user/$repo/ubuntu/ $distribution main
deb-src [arch=$(dpkg --print-architecture) signed-by=$key_path] https://ppa.launchpadcontent.net/$user/$repo/ubuntu/ $distribution main
EOF
  sudo apt-get update
fi
