#!/bin/bash
set -eu
if [ $# -ne 1 ]; then
  >&2 cat <<EOF
Usage: $0 ppa:user/repo
EOF
  exit 2
fi

user_and_repo=${1#*:}
user=${user_and_repo%/*}
repo=${user_and_repo#*/}

distribution=$(lsb_release -cs)

key_dir=/usr/local/share/keyrings
key_basename="$user-ubuntu-$repo-$distribution"
key_path="$key_dir/$key_basename.gpg"

apt_list_path="/etc/apt/sources.list.d/$user-ubuntu-$repo-$distribution.list"

if [ ! -f "$key_path" ]; then
  # make sure commands are installed
  type curl gpg install > /dev/null

  key_fingerprint=$(curl -sS "https://launchpad.net/~$user/+archive/ubuntu/$repo" | grep -A 1 -F '<dt>Fingerprint:</dt>' | tail -1 | sed 's| *</*dd>||g')
  gpg_key_url="https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x$key_fingerprint"

  tmp_keyring=$(mktemp /tmp/tmp-keyring.XXXXXXXXXX.gpg)
  curl -sS "$gpg_key_url" | gpg --no-default-keyring --keyring "$tmp_keyring" --import -
  
  tmp_keyring2=$(mktemp /tmp/tmp-keyring.XXXXXXXXXX.gpg)
  gpg --no-default-keyring --keyring "$tmp_keyring" --export --output "$tmp_keyring2" --yes
  
  sudo install -D --mode 0644 "$tmp_keyring2" "$key_path"
  rm "$tmp_keyring" "$tmp_keyring2"
fi

if [ ! -f "$apt_list_path" ]; then
  cat <<EOF | sudo tee "$apt_list_path" > /dev/null
deb [signed-by=$key_path] https://ppa.launchpadcontent.net/$user/$repo/ubuntu/ $distribution main
deb-src [signed-by=$key_path] https://ppa.launchpadcontent.net/$user/$repo/ubuntu/ $distribution main
EOF
  sudo apt-get update
fi
